name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: String Manipulation Test
      id: string-manipulation-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: String Manipulation Test
        setup-command: ''
        command: python test_script.py
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        STRING-MANIPULATION-TEST_RESULTS: "${{steps.string-manipulation-test.outputs.result}}"
      with:
        runners: string-manipulation-test
